#!/bin/sh
#
# sxhkd key bindings
#


########################################################
# General bindings
########################################################
# terminal emulator
super + Return
	$TERMINAL

# Dopdown terminal
super + shift + Return
	scratchpad dropdown

# Ranger terminal
super + alt + Return
	scratchpad ranger

# Web search menu
super + w
	$HOME/bin/websearch

# browser
super + shift + w
	$BROWSER

# program launcher
super + {_,shift + }p
	rofi -modi run,drun,ssh -show {run,drun}

# Alt-tab - Cycle opened windows
alt + Tab
	rofi -modi window -show window -show-icons

# Screen lock
super + alt + Escape
	i3lock -e -f -c 000000 -i .config/wall.png

# Logout/shutdown/reboot
super + alt + q
	$HOME/bin/session

# reload sxhkd configuration
super + alt + c
	pkill -USR1 -x sxhkd


########################################################
# BSPWM Bindings
########################################################
# restart bspwm
super + alt + r
	bspc wm -r

#
# Window state/flags
#

# close and kill
super + {_,shift + }q
	bspc node -{c,k}

# Toggle fullscreen
super + space
	bspc node focused -t \~fullscreen

# Toggle floating
super + shift + space
	bspc node focused -t \~floating

# Toggle sticky
super + shift + s
	bspc node -g sticky={on,off}

# set the window state
super + {t,shift + t}
	bspc node -t {tiled,pseudo_tiled}

# set the node flags
super + ctrl + {m,l,p}
	bspc node -g {marked,locked,private}

# alternate between the tiled and monocle layout
super + m
	bspc desktop -l next

#
# Focus
#

# Focus on window in direction
super + {h,j,k,l}
	bspc node -f {west,south,north,east}

# focus the next/previous node in the current desktop
super + bracket{left,right}
	bspc node -f {prev,next}.local

# focus the next/previous desktop in the current monitor
super + shift + bracket{left,right}
	bspc desktop -f {prev,next}.local

# focus the last node/desktop
super + shift + {6,Tab}
	bspc {node,desktop} -f last

# focus or send to the given desktop
super + {_,shift + }{1-9,0}
	bspc {desktop -f,node -d} '^{1-9,10}'

# focus the node for the given path jump
#super + {p,b,comma,period}
#	bspc node -f @{parent,brother,first,second}

#
# Swap / Move / Resize
#

# Mouse resize using super + right mouse click

# Move node
super + shift + {h,j,k,l}
	bspc node -s {west,south,north,east}

# Resize node
super + alt + {h,j,k,l}
	~/.config/bspwm/resize.sh {west,south,north,east}

# Swap current node and biggest local node
super + alt + b
	bspc node -s biggest.local || bspc node -s next.local

# swap the current node and the biggest node
#super + g
#	bspc node -s biggest

# send the newest marked node to the newest preselected node
super + shift + y
	bspc node newest.marked.local -n newest.!automatic.local

# move a floating window
super + {Left,Down,Up,Right}
	bspc node -v {-20 0,0 20,0 -20,20 0}

#
# preselect
#

# preselect the direction
super + ctrl + {h,j,k,l}
	bspc node -p {west,south,north,east}

# preselect the ratio
super + ctrl + {1-9}
	bspc node -o 0.{1-9}


########################################################
# Media keys
########################################################
XF86Explorer
	scratchpad ranger
XF86HomePage
	$BROWSER
XF86Calculator
	gnome-calculator
XF86Tools
	spotify
XF86AudioPlay
	playerctl play-pause
XF86AudioStop
	playerctl stop
XF86AudioPrev
	playerctl previous
XF86AudioNext
	playerctl next
XF86AudioMute
	pactl set-sink-mute 0 toggle
XF86AudioLowerVolume
	pactl set-sink-volume 0 -5%
XF86AudioRaiseVolume
	pactl set-sink-volume 0 +5%


