#!/bin/sh


bspc monitor HDMI2 -d 1 2 3 4 5
bspc monitor HDMI3 -d 6 7 8 9 0

bspc config top_padding    34
bspc config bottom_padding 0
bspc config border_width   3
bspc config window_gap     8

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer false

bspc config focused_border_color         "#458588"
bspc config normal_border_color          "#282828"
bspc config presel_border_color          "#fabd2f"
bspc config urgent_border_color          "#fb4934"
bspc config focused_private_border_color "#ebdbb2"

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

# Dropdown
bspc rule -a dropdown sticky=on state=floating hidden=on
$TERMINAL --class dropdown -e "bash -i" &
# File manager
bspc rule -a filmanager sticky=on state=floating hidden=on
$TERMINAL --class filemanager -e "lf" &
